### PR TITLE
Add NZ timezones.

### PR DESCRIPTION
**Pull request by chrisforbes**

### CODE REVIEW

**Comment by chrisforbes** [comment]
@kkaefer any plan to merge this? It's ugly having to carry a patch to get proper date/time formatting in TileMill for all the NZ users I support.

**Comment by kkaefer** [comment]
Whoops sorry, this slipped through my notifications screen. Thanks for the patch!

**Comment by kkaefer** [comment]
Published 1.0.4. This will be in the next release of TileMill.

**Comment by chrisforbes** [comment]
Awesome, thanks

**Pull request merged**
